=== Relintai/pandemonium_engine/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" />
			<xs:attribute type="xs:string" name="category" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Relintai/pandemonium_engine/doc/classes/BlobShadow.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="BlobShadow" inherits="Spatial" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Casts spherical or capsular geometrical shadows.
	</brief_description>
	<description>
		[BlobShadow] provides an alternative to traditional shadow maps, by casting simple geometrical soft shadows.
		Provided the number of runtime shadows is kept low, this can provide better performance than shadow maps.
		It is a good option when combined with lightmaps.
		[BlobShadow] requires a [Light] set to cast blob shadows, and should usually be used in conjunction with a [BlobFocus], to determine where shadows should be prioritized.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_radius" qualifiers="const">
			<return type="float" />
			<argument index="0" name="index" type="int" />
			<description>
			</description>
		</method>
		<method name="set_radius">
			<return type="void" />
			<argument index="0" name="index" type="int" />
			<argument index="1" name="radius" type="float" />
			<description>
				Only radius index 0 is used with spheres.
				Radius index 0 and 1 are used with capsules.
			</description>
		</method>
	</methods>
	<members>
		<member name="offset" type="Vector3" setter="set_offset" getter="get_offset">
			Offset is used to determine the shape of capsules, allowing elongation in any direction.
		</member>
		<member name="offset_radius" type="float" setter="set_radius" getter="get_radius">
			Radius of offset side of a capsule.
			[b]Note:[/b] Unused for spheres.
		</member>
		<member name="radius" type="float" setter="set_radius" getter="get_radius" default="1.0">
			Radius of the sphere (or origin side of a capsule).
		</member>
		<member name="type" type="int" setter="set_shadow_type" getter="get_shadow_type" enum="BlobShadow.BlobShadowType" default="0">
			Allows choosing caster type, sphere or capsule.
		</member>
	</members>
	<constants>
		<constant name="BLOB_SHADOW_SPHERE" value="0" enum="BlobShadowType">
		</constant>
		<constant name="BLOB_SHADOW_CAPSULE" value="1" enum="BlobShadowType">
		</constant>
	</constants>
</class>

=== Relintai/pandemonium_engine/modules/godot_dragonbones/doc_classes/GDBone2D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="GDBone2D" inherits="Bone2D" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="get_bone_animation_position">
			<return type="Vector2" />
			<description>
				Get Vector2 of bone position
			</description>
		</method>
		<method name="get_bone_global_position">
			<return type="Vector2" />
			<description>
				Get global position of bones Vector 2D
			</description>
		</method>
		<method name="get_bone_global_rotation">
			<return type="float" />
			<description>
				Get float of bone rotation global
			</description>
		</method>
		<method name="get_bone_global_scale">
			<return type="Vector2" />
			<description>
				Get scale of global bone
			</description>
		</method>
		<method name="get_bone_name">
			<return type="String" />
			<description>
				Get bone name
			</description>
		</method>
		<method name="get_bone_offset_position">
			<return type="Vector2" />
			<description>
				Get bone offset pos
			</description>
		</method>
		<method name="get_bone_origin_position">
			<return type="Vector2" />
			<description>
				Get bone origin position Vec2D
			</description>
		</method>
		<method name="get_bone_position">
			<return type="Vector2" />
			<description>
				Get bone bone position in 2D
			</description>
		</method>
		<method name="get_bone_rotation">
			<return type="float" />
			<description>
				Get bone rotation float
			</description>
		</method>
		<method name="get_bone_scale">
			<return type="Vector2" />
			<description>
				Get bone scale 2D vec
			</description>
		</method>
		<method name="has_data">
			<return type="bool" />
			<description>
				Check bone has data
			</description>
		</method>
		<method name="set_bone_global_position">
			<return type="void" />
			<argument index="0" name="new_position" type="Vector2" />
			<description>
				Set bone global pos from Vec 2D
			</description>
		</method>
		<method name="set_bone_global_rotation">
			<return type="void" />
			<argument index="0" name="deg_in_rad" type="float" />
			<description>
				Set bone global rotation from float
			</description>
		</method>
		<method name="set_bone_global_scale">
			<return type="void" />
			<argument index="0" name="new_scale" type="Vector2" />
			<description>
				Set bone global scale from Vec 2D
			</description>
		</method>
		<method name="set_bone_position">
			<return type="void" />
			<argument index="0" name="new_position" type="Vector2" />
			<description>
				Set bone pos from Vec2D
			</description>
		</method>
		<method name="set_bone_rotation">
			<return type="void" />
			<argument index="0" name="deg_in_rad" type="float" />
			<description>
				Set bone rotation in deg radian
			</description>
		</method>
		<method name="set_bone_scale">
			<return type="void" />
			<argument index="0" name="new_scale" type="Vector2" />
			<description>
				Set bone scale from Vec2D
			</description>
		</method>
	</methods>
	<constants>
	</constants>
</class>
